name: "KiCAD CI/CD for Icarus Controller"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  generate-outputs:
    name: "KiCAD Outputs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init --recursive
      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: hardware/icarus/icarus.kibot.yaml
          dir: output
          schema: 'hardware/icarus/icarus.kicad_sch'
          board: 'hardware/icarus/icarus.kicad_pcb'
          verbose: 1
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output

  docs:
    name: Docs
    runs-on: ubuntu-latest
    needs: [generate-outputs]

    steps:
      - uses: actions/checkout@v1
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: cargo install --git https://github.com/nnarain/mdbook-file-search
      - run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - run: cargo install mdbook-d2
      - uses: actions/download-artifact@v2
        with:
          name: output
          path: hardware/icarus/out
      - run: cd docs && mdbook build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/book

  release:
    name: Deploy to Github Releases
    runs-on: ubuntu-latest
    needs: [generate-outputs]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: output
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./icarus-design_docs.zip
            ./icarus-jlcpcb_fab.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
