name: "KiCAD CI/CD for Icarus Controller"

on:
  push:
    tags:
      - "*"
    branches:
      - issue8-ci

jobs:
  fabrication-outputs:
    name: "KiCAD Fabrication Outputs"
    runs-on: ubuntu-latest
    # container: setsoft/kicad_auto:dev_k6
    steps:
      - uses: actions/checkout@v1
      - runs: git submodule update --init --recursive
      - uses: INTI-CMNB/KiBot@v1_k6
        with:
          config: hardware/icarus/icarus.kibot.yaml
          dir: output
          schema: '*.kicad_sch'
          board: '*.kicad_pcb'
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
